Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2020-09, with the labels that each got.

#299 multicast readme and example updates
  client/EXAMPLES.md
  client/README.md
  client/files/images/ds-multicast-client-cloud-gke-architecture.png
  client/files/images/ds-multicast-client-quick-start-output.png
Labels: client, documentation, enhancement

#296 WIP: Remove firebase dependency
  api/README.md
  api/config/ds-api-mgr-role-definition.yaml
  api/v1alpha/istio-manifests/1.4/authn/default-jwt-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-data-consumers-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml
  api/v1alpha/src/index.js
  frontend/deploy.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/public/config/config.json
  frontend/src/api/mock/data/settings.json
  frontend/src/api/mock/data/settings_cds-demo-1.json
  frontend/src/api/mock/data/settings_cds-demo-2.json
  frontend/src/api/mock/data/settings_local.json
  frontend/src/api/mock/index.js
  frontend/src/api/server/index.js
  frontend/src/components/ActivationCard.vue
  frontend/src/components/Header.vue
  frontend/src/components/MyDashboardCard.vue
  frontend/src/config.js
  frontend/src/main.js
  frontend/src/mixins/authMixin.js
Labels: cleanup, enhancement

#301 updating BigQuery init to include projectId where applicable
  api/v1alpha/package-lock.json
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/datasets/dataManager.js
  api/v1alpha/src/lib/metaManager.js
  api/v1alpha/src/policies/dataManager.js
  api/v1alpha/src/procurements/dataManager.js
  shared/bigqueryUtil.js
Labels: api, bug

#307 remove the namespace source requirement for knative serving policy
  api/v1alpha/istio-manifests/1.4/authz/allow-knative-serving-policy.yaml
Labels: api, bug

#308 Marketplace vm solution script updates
  marketplace/create-vm-solution-package.sh
  marketplace/delete-vm-solution-components-from-gcp.sh
  marketplace/install-datashare-prerequisites.sh
  marketplace/remove-elevated-permissions-from-cloudbuild-deploymentmgr.sh
  marketplace/reset-gcp-project-for-testing.sh
  marketplace/update-compute-service-account-with-securityadmin-role.sh
Labels: enhancement

#302 Procurement permission fixes and serviceAccount sharing support
  api/config/ds-api-mgr-role-definition.yaml
  api/deploy.sh
  api/devDeploy.sh
  api/v1alpha/package.json
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/admin/bq/procedure/permissionsDiff.sql
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/datasets/dataManager.js
  api/v1alpha/src/lib/metaManager.js
  api/v1alpha/src/procurements/dataManager.js
  frontend/src/components/AccountsCard.vue
  frontend/src/components/ActivationCard.vue
  frontend/src/components/DatasetsCard.vue
  frontend/src/components/EditAccount.vue
  frontend/src/components/EditIngestion.vue
  frontend/src/components/EditPolicy.vue
  frontend/src/components/EditView.vue
  frontend/src/components/MyDashboardCard.vue
  frontend/src/components/PoliciesCard.vue
  frontend/src/components/ProcurementsCard.vue
  frontend/src/components/SpotFulfillmentCard.vue
  frontend/src/components/ViewsCard.vue
  ingestion/batch/index.js
Labels: bug, cleanup

#314 fix marketplace jwt audience authz configuration
  api/README.md
  api/v1alpha/istio-manifests/1.4/authz/allow-marketplace-service-account-policy.tmpl.yaml
Labels: api, documentation, enhancement

#316 Allowing marketplace to post to accounts:register
  api/deploy.sh
  api/v1alpha/istio-manifests/1.4/authn/default-jwt-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-marketplace-service-account-policy.tmpl.yaml
Labels: bug

#324 Marketplace link is opening the solution link without a projectId specified
  frontend/src/urlHelper.js
Labels: bug

#328 Marketplace vm solution v0.5.5
  api/deploy_ds_api.py
  api/deploy_ds_api.yaml
  marketplace/PREREQUISITES.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.4.zip
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.5.zip
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
  marketplace/vm-solution/test_config.yaml
Labels: bug, documentation

#329 Adjust UI messaging in Policy dialogue
  frontend/src/components/EditPolicy.vue
Labels: cleanup

#330 Doc updates
  README.md
Labels: cleanup, documentation

#333 fixes #331 - updated prereqs documentation, fixed broken link, update…
  marketplace/PREREQUISITES.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.6.zip
  marketplace/vm-solution/datashare-vm.jinja.display
Labels: bug, documentation
