Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2020-10, with the labels that each got.

#334 Release 0.5.7 - VM dependsOn the GKE cluster now; updated release documentation.
  marketplace/README.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.7.zip
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
Labels: bug

#337 Unable to reject non associated datashare policy
  frontend/src/components/ProcurementsCard.vue
Labels: bug

#340 Deployment document updates
  APPLY_ISTIO_POLICIES.md
  CREDENTIAL_SETUP.md
  DEPLOY.md
  DOMAIN_SETUP.md
  ENVIRONMENT_VARIABLES.md
  README.md
  api/v1alpha/src/lib/metaManager.js
  assets/credentials/1-oauth_consent_screen.png
  assets/credentials/2-oauth_consent_screen.png
  assets/deploy/1-datashare_launch.png
  assets/deploy/10-verify_api_domain.png
  assets/deploy/11-api_domain_dns_record.png
  assets/deploy/12-api_a_record.png
  assets/deploy/13-zone_details.png
  assets/deploy/2-select_product.png
  assets/deploy/3-deploy.png
  assets/deploy/4-deploy-completed.png
  assets/deploy/5-verify_ui_domain.png
  assets/deploy/6-ui_domain_dns_records.png
  assets/deploy/7-create_a_records.png
  assets/deploy/8-create_aaaa_records.png
  assets/deploy/9-zone_details.png
  assets/domain/1-create_zone.png
  assets/domain/2-zone_details.png
  assets/domain/3-registrar_setup.png
  assets/domain/4-top_level_ns_setup.png
  assets/domain/5-verify_domain_ownership.png
  assets/domain/6-create_txt_record.png
  assets/domain/7-zone_details.png
  assets/domain/8-domain_verified.png
  assets/domain/cloud_dns.png
  marketplace/PREREQUISITES.md
Labels: documentation

#348 Marketplace vm solution v0.5.8
  api/deploy_ds_api.py
  frontend/deploy_ui_cloud_run.py
  frontend/deploy_ui_cloud_run.py.schema
  frontend/deploy_ui_cloud_run.yaml
  marketplace/PREREQUISITES.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.8.zip
  marketplace/vm-solution/cloud_function.py
  marketplace/vm-solution/cloud_function.py.schema
  marketplace/vm-solution/cluster.py
  marketplace/vm-solution/common/vm_instance.py
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
  marketplace/vm-solution/test_config.yaml
Labels: bug, enhancement

#351 adding new istio policies for letsencrypt acme challenge endpoint. fi…
  api/README.md
  api/v1alpha/istio-manifests/1.4/authn/default-jwt-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-letsencrypt-acme-challenge-policy.yaml
Labels: api, bug

#335 Consumers should only see my products
  api/v1alpha/istio-manifests/1.4/authz/allow-data-consumers-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml
  api/v1alpha/src/auth/index.js
  api/v1alpha/src/index.js
  frontend/src/api/server/index.js
  frontend/src/components/Header.vue
  frontend/src/main.js
  frontend/src/router.js
  frontend/src/store.js
Labels: bug, cleanup, enhancement

#353 Fix for authorization policies and broken marketplace dashboard url
  CREDENTIAL_SETUP.md
  api/README.md
  api/v1alpha/istio-manifests/1.4/authn/default-jwt-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-data-consumers-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-data-consumers-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-global-docs-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-global-preflight-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-marketplace-service-account-policy.yaml
  api/v1alpha/src/accounts/index.js
  api/v1alpha/src/index.js
  api/v1alpha/src/lib/config.js
  api/v1alpha/src/lib/fb/auth.js
  api/v1alpha/src/procurements/index.js
  frontend/src/components/ActivationCard.vue
  frontend/src/components/Header.vue
  frontend/src/components/MyProductsCard.vue
  frontend/src/router.js
  frontend/src/store.js
  frontend/src/views/MyDashboard.vue
  frontend/src/views/MyProducts.vue
  frontend/user-guide/MARKETPLACE_INTEGRATION.md
  shared/commonUtil.js
  shared/test/commonUtilTest.js
Labels: bug, ui

#359 Upgrade script and documentation
  ENVIRONMENT_VARIABLES.md
  README.md
  UPGRADE.md
  api/deploy.sh
  upgrade.sh
Labels: documentation, enhancement

#360 Error thrown when deleting a dataset
  UPGRADE.md
  api/v1alpha/src/admin/bq/procedure/permissionsDiff.sql
  api/v1alpha/src/datasets/dataManager.js
Labels: bug

#362 Add delete permission for datasets to ds-api-mgr-role-definition.yaml
  api/config/ds-api-mgr-role-definition.yaml
Labels: bug

#363 Upgrade script project_id set fix
  upgrade.sh
Labels: bug

#364 UI Config fix
  api/v1alpha/istio-manifests/1.4/authz/allow-data-consumers-policy.yaml
  frontend/public/config/config.json
Labels: bug

#367 Documentation for modifying data producers
  README.md
  UPDATE_DATA_PRODUCERS.md
Labels: documentation

#361 Marketplace vm solution v0.6.0
  api/deploy_ds_api.py
  api/deploy_ds_api.yaml
  marketplace/PREREQUISITES.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.0.zip
  marketplace/reset-gcp-project-for-testing.sh
  marketplace/vm-solution/c2d_deployment_configuration.json
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
  marketplace/vm-solution/waiter.jinja
  marketplace/vm-solution/waiter.jinja.schema
Labels: bug, documentation, enhancement

#368 Security warning fixes
  api/v1alpha/package-lock.json
  frontend/package-lock.json
  shared/package-lock.json
Labels: cleanup
