Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2020-06, with the labels that each got.

#147 Fix for view and dataset redirect
  frontend/src/components/DatasetsCard.vue
  frontend/src/components/ViewsCard.vue
Labels: bug

#150 Fixes: skip rows error when loading non-csv, missing role permission
  api/config/cds-api-mgr-role-definition.yaml
  ingestion/batch/configurationManager.js
Labels: bug

#153 Fix for view sync failure when no expiry defined
  api/v1alpha/src/admin/dataManager.js
Labels: bug

#158 Multicast client prototype
  client/.gitignore
  client/Dockerfile
  client/EXAMPLES.md
  client/README.md
  client/cmd/dmc/LICENSE
  client/cmd/dmc/cmd/broadcast.go
  client/cmd/dmc/cmd/cmd_version.go
  client/cmd/dmc/cmd/input.go
  client/cmd/dmc/cmd/listen.go
  client/cmd/dmc/cmd/multicast.go
  client/cmd/dmc/cmd/publish.go
  client/cmd/dmc/cmd/root.go
  client/cmd/dmc/cmd/socket.go
  client/cmd/dmc/main.go
  client/files/images/ds-multicast-client-private-cloud-architecture.png
  client/internal/injestion/injestion.go
  client/internal/pubsubutil/pubsubutil.go
  client/internal/validate/validate.go
  client/kubernetes-manifests/dmc-listener-service/configmaps.yaml
  client/kubernetes-manifests/dmc-listener-service/deployment.yaml
  client/kubernetes-manifests/dmc-listener-service/lb-service.yaml
  client/kubernetes-manifests/dmc-listener-service/service.yaml
  client/kubernetes-manifests/dmc-producer-job/configmaps.yaml
  client/kubernetes-manifests/dmc-producer-job/job.yaml
  client/kubernetes-manifests/dmc-publisher-service/configmaps.yaml
  client/kubernetes-manifests/dmc-publisher-service/deployment.yaml
  client/kubernetes-manifests/dmc-publisher-service/lb-service.yaml
  client/kubernetes-manifests/dmc-publisher-service/service.yaml
  client/kubernetes-manifests/tcpreplay-job/configmaps.yaml
  client/kubernetes-manifests/tcpreplay-job/job.yaml
  client/pkg/multicast/broadcaster.go
  client/pkg/multicast/connection.go
  client/pkg/multicast/listener.go
  client/pkg/multicast/publisher.go
  client/skaffold.yaml
Labels: documentation, enhancement

#168 API authentication and authorization with RBAC features
  api/README.md
  api/v1alpha/.gitignore
  api/v1alpha/istio-manifests/1.4/authn/default-jwt-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-data-consumers-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-global-docs-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-global-preflight-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-knative-serving-policy.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-marketplace-service-account-policy.tmpl.yaml
Labels: api, enhancement

#169 updated docs with DRS note. closed #149
  api/README.md
  frontend/README.md
Labels: documentation

#136 WIP: Marketplace approval integration and general fixes
  .github/workflows/nodejs.yml
  api/README.md
  api/v1alpha/Dockerfile
  api/v1alpha/istio-manifests/1.4/authz/allow-data-consumers-policy.tmpl.yaml
  api/v1alpha/istio-manifests/1.4/authz/allow-marketplace-service-account-policy.tmpl.yaml
  api/v1alpha/kubernetes-manifests/cds-api/deployment.yaml
  api/v1alpha/package-lock.json
  api/v1alpha/package.json
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/accounts/index.js
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/index.js
  api/v1alpha/src/lib/config.js
  api/v1alpha/src/lib/fb/auth.js
  api/v1alpha/src/lib/metaManager.js
  api/v1alpha/src/policies/dataManager.js
  api/v1alpha/src/policies/index.js
  api/v1alpha/src/procurements/dataManager.js
  api/v1alpha/src/procurements/index.js
  cloudbuild.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/api/mock/data/marketplaceRequests.json
  frontend/src/api/mock/index.js
  frontend/src/api/server/index.js
  frontend/src/assets/datashare-alpha-24px.svg
  frontend/src/components/AccountsCard.vue
  frontend/src/components/ActivationCard.vue
  frontend/src/components/AdminCard.vue
  frontend/src/components/EditAccount.vue
  frontend/src/components/EditPolicy.vue
  frontend/src/components/Footer.vue
  frontend/src/components/Header.vue
  frontend/src/components/MyDashboardCard.vue
  frontend/src/components/PoliciesCard.vue
  frontend/src/components/ProcurementsCard.vue
  frontend/src/components/Welcome.vue
  frontend/src/main.js
  frontend/src/router.js
  frontend/src/store.js
  frontend/src/views/Activation.vue
  frontend/src/views/Home.vue
  frontend/src/views/MyDashboard.vue
  frontend/src/views/Procurements.vue
  frontend/src/views/Restricted.vue
  ingestion/batch/package-lock.json
  ingestion/batch/package.json
  shared/commerceProcurementUtil.js
  shared/index.js
  shared/package-lock.json
  shared/package.json
  shared/testProcurementUtil.js
Labels: enhancement

#170 updating consumer definition. closes #157
  README.md
Labels: bug, documentation
