Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2020-08, with the labels that each got.

#272 fixes #271 - changed API deployment name to ds-api from cds-api
  api/v1alpha/cloudbuild.yaml
Labels: bug

#267 Marketplace integration doc updates
  frontend/user-guide/MARKETPLACE_INTEGRATION.md
Labels: documentation

#270 Ingestion deploy script path fixes
  examples/weather/README.md
  examples/weather/data/weather.observation.csv.gz
  examples/weather/observation/config/schema.json
  examples/weather/observation/config/transform.sql
  examples/weather/observation/data/weather.observation.csv
  ingestion/batch/bin/deploy.sh
  ingestion/batch/index.js
  ingestion/batch/package.json
Labels: bug

#274 Adding year to date in weather example
  examples/weather/observation/config/schema.json
  examples/weather/observation/data/weather.observation.csv
Labels: bug, cleanup

#276 Handle label column as a string to avoid conversion errors
  api/devDeploy.sh
  api/v1alpha/src/datasets/views/sqlBuilder.js
Labels: bug

#278 Email address should be caller for auto-activation
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/procurements/dataManager.js
Labels: bug

#279 Hide token on activation page
  frontend/src/components/ActivationCard.vue
Labels: cleanup, ui

#281 Audit fixes
  frontend/package-lock.json
  frontend/package.json
  ingestion/batch/package-lock.json
Labels: cleanup

#282 Add ability to filter on entitlement state in the procurement request ui
  api/v1alpha/src/procurements/dataManager.js
  api/v1alpha/src/procurements/index.js
  frontend/src/api/server/index.js
  frontend/src/components/ProcurementsCard.vue
  frontend/src/store.js
Labels: enhancement, ui

#283 Ability to add customize message/link to consumers on account addition process
  api/v1alpha/istio-manifests/1.4/authz/allow-data-consumers-policy.tmpl.yaml
  api/v1alpha/src/admin/index.js
  frontend/src/api/server/index.js
  frontend/src/components/MyDashboardCard.vue
  frontend/src/store.js
Labels: enhancement, ui

#284 Fixes issue where initial ui load returns blank page
  frontend/src/api/mock/index.js
  frontend/src/main.js
Labels: bug, ui

#285 Actions should only show for pending request states
  frontend/src/components/ProcurementsCard.vue
Labels: bug

#289 Marketplace Deployment v0.5.3 - fixes #288
  marketplace/PREREQUISITES.md
  marketplace/README.md
  marketplace/images/iam-add-new-member.png
  marketplace/images/iam-assign-members-to-sa.png
  marketplace/images/iam-assign-roles-to-sa.png
  marketplace/images/iam-create-sa.png
  marketplace/images/iam-select-service-account.png
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.3.zip
  marketplace/vm-solution/cluster.py
  marketplace/vm-solution/common/vm_instance.py
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
  marketplace/vm-solution/test_config.yaml
Labels: bug, documentation, enhancement

#291 adding go module support for multicast client
  client/Dockerfile
  client/README.md
  client/cmd/dmc/cmd/broadcast.go
  client/cmd/dmc/cmd/listen.go
  client/cmd/dmc/cmd/publish.go
  client/go.mod
  client/go.sum
  client/kubernetes-manifests/dmc-producer-job/configmaps.yaml
  client/pkg/multicast/broadcaster.go
  client/pkg/multicast/connection.go
Labels: client, documentation, enhancement

#292 Move firebase settings to cloud run environmental variables
  api/v1alpha/src/accounts/index.js
  api/v1alpha/src/admin/index.js
  frontend/Dockerfile
  frontend/README.md
  frontend/docker/entrypoint.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/public/config/config.json
  frontend/src/App.vue
  frontend/src/api/mock/index.js
  frontend/src/api/server/index.js
  frontend/src/components/Header.vue
  frontend/src/components/MyDashboardCard.vue
  frontend/src/components/SettingsCard.vue
  frontend/src/components/SetupBanner.vue
  frontend/src/config.js
  frontend/src/main.js
  frontend/src/router.js
  frontend/src/store.js
  frontend/src/views/Settings.vue
  frontend/vue.config.js
Labels: cleanup, enhancement, ui
