Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2020-07, with the labels that each got.

#172 #141 Handle non authenticated 403 redirect
  frontend/src/api/server/index.js
Labels: cleanup

#171 Cds to ds renaming
  .github/CODEOWNERS
  api/README.md
  api/config/ds-api-mgr-role-definition.yaml
  api/deploy_ds_api.py
  api/files/images/ds-api-entitlement-architecture.png
  api/files/images/ds-api-spot-architecture.png
  api/files/images/ds-api-spot-mgr-gcs-bucket-permissions.png
  frontend/Dockerfile
  frontend/src/assets/cds-architecture.png
  frontend/src/assets/ds-architecture.png
  frontend/src/components/Welcome.vue
  frontend/src/views/Home.vue
Labels: cleanup

#175 Fixed Cloud Function deployment in new projects
  marketplace/delete-vm-solution-components-from-gcp.sh
  marketplace/install-datashare-prerequisites.sh
  marketplace/reset-gcp-project-for-testing.sh
  marketplace/vm-solution/datashare-vm.jinja
Labels: bug

#178 Marketplace VM solution - updates for Cloud Build
  marketplace/PREREQUISITES.md
  marketplace/README.md
  marketplace/images/IAM.png
  marketplace/images/cloud-shell.png
  marketplace/images/iam-add-another-role.png
  marketplace/images/iam-compute-sa.png
  marketplace/images/iam-save-button.png
  marketplace/images/iam-search-security-admin.png
  marketplace/remove-elevated-permissions-from-cloudbuild-deploymentmgr.sh
  marketplace/reset-gcp-project-for-testing.sh
  marketplace/update-compute-service-account-with-securityadmin-role.sh
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: bug, cleanup, documentation, enhancement

#180 Adding logo card to readme
  README.md
  card.png
Labels: documentation

#179 Table-based policy UI and data support
  api/v1alpha/cloudbuild.yaml
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/index.js
  api/v1alpha/src/lib/config.js
  api/v1alpha/src/lib/metaManager.js
  api/v1alpha/src/policies/dataManager.js
  api/v1alpha/src/policies/index.js
  frontend/src/components/EditPolicy.vue
  shared/bigqueryUtil.js
  shared/test/bigQueryUtilTest.js
  shared/test/testSetup.js
Labels: enhancement

#183 Table based permission sync feature
  api/v1alpha/package-lock.json
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/admin/bq/procedure/permissionsDiff.sql
  api/v1alpha/src/admin/bq/schema/account.json
  api/v1alpha/src/admin/bq/schema/authorizedView.json
  api/v1alpha/src/admin/bq/schema/policy.json
  api/v1alpha/src/admin/bq/views/currentAccount.sql
  api/v1alpha/src/admin/bq/views/currentAuthorizedView.sql
  api/v1alpha/src/admin/bq/views/currentPolicy.sql
  api/v1alpha/src/admin/bq/views/currentUserPermission.sql
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/datasets/dataManager.js
  api/v1alpha/src/datasets/views/sqlBuilder.js
  api/v1alpha/src/lib/config.js
  api/v1alpha/src/lib/metaManager.js
  api/v1alpha/src/policies/dataManager.js
  frontend/src/components/EditPolicy.vue
  shared/bigqueryUtil.js
  shared/package-lock.json
  shared/package.json
Labels: bug, cleanup, enhancement

#184 Api deployment readme fixes
  api/README.md
Labels: api, documentation

#187 adding xip.io wildcard DNS instructions
  api/README.md
Labels: api, documentation

#185 Marketplace VM solution - Cloud Run managed GKE deployment
  api/deploy_ds_api.py
  api/deploy_ds_api.py.schema
  marketplace/README.md
  marketplace/delete-vm-solution-components-from-gcp.sh
  marketplace/install-datashare-prerequisites.sh
  marketplace/remove-elevated-permissions-from-cloudbuild-deploymentmgr.sh
  marketplace/reset-gcp-project-for-testing.sh
  marketplace/vm-solution/cluster.py
  marketplace/vm-solution/cluster.py.schema
  marketplace/vm-solution/cluster.yaml
  marketplace/vm-solution/common/vm_instance.py
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
  marketplace/vm-solution/waiter.jinja
Labels: enhancement

#177 Handle blank transform.sql as select *
  ingestion/batch/index.js
Labels: bug, cleanup, enhancement

#192 #191 - Fixes issue where 'My Products' is showing non-marketplace configured policy records
  api/v1alpha/src/policies/dataManager.js
Labels: bug

#188 Rename manifest path
  frontend/kubernetes-manifests/ds-frontend-ui/deployment.yaml
  frontend/kubernetes-manifests/ds-frontend-ui/lb-service.yaml
  frontend/kubernetes-manifests/ds-frontend-ui/service.yaml
  frontend/skaffold.yaml
Labels: cleanup

#194 Fixes issue where non-managed datasets were available for selection in the destination dataset list
  api/v1alpha/src/datasets/dataManager.js
  api/v1alpha/src/datasets/index.js
  frontend/src/api/server/index.js
  frontend/src/components/DatasetsCard.vue
  frontend/src/components/EditIngestion.vue
  frontend/src/components/EditPolicy.vue
  frontend/src/components/EditView.vue
  frontend/src/store.js
  shared/bigqueryUtil.js
Labels: bug, cleanup

#210 fixes #205 - boolean checkbox to deploy to GKE cluster was not workin…
  api/deploy_ds_api.py
  marketplace/vm-solution/common/vm_instance.py
  marketplace/vm-solution/datashare-vm.jinja
Labels: bug

#202 Initial UI documentation
  api/README.md
  frontend/README.md
  frontend/src/components/Header.vue
  frontend/user-guide/ACCOUNTS.md
  frontend/user-guide/ADMIN.md
  frontend/user-guide/AUTHORIZED_VIEWS.md
  frontend/user-guide/DATASETS.md
  frontend/user-guide/MARKETPLACE_INTEGRATION.md
  frontend/user-guide/MY_PRODUCTS.md
  frontend/user-guide/POLICIES.md
  frontend/user-guide/PROCUREMENT_REQUESTS.md
  frontend/user-guide/README.md
  frontend/user-guide/SETTINGS.md
  frontend/user-guide/assets/accounts_list_ui.png
  frontend/user-guide/assets/add_service_features.png
  frontend/user-guide/assets/add_service_plans.png
  frontend/user-guide/assets/admin_ui.png
  frontend/user-guide/assets/authorized_views_ui.png
  frontend/user-guide/assets/bigquery_label.png
  frontend/user-guide/assets/datashare_list_ui.png
  frontend/user-guide/assets/delete_dataset.png
  frontend/user-guide/assets/edit_dataset.png
  frontend/user-guide/assets/features_and_pricing.png
  frontend/user-guide/assets/firebase_config.png
  frontend/user-guide/assets/marketplace_features.png
  frontend/user-guide/assets/my_products_detail.png
  frontend/user-guide/assets/my_products_ui.png
  frontend/user-guide/assets/nav_menu.png
  frontend/user-guide/assets/policies_list_ui.png
  frontend/user-guide/assets/procurement_actions.png
  frontend/user-guide/assets/procurement_requests_ui.png
  frontend/user-guide/assets/purchase_flow_1.png
  frontend/user-guide/assets/purchase_flow_2.png
  frontend/user-guide/assets/purchase_flow_3.png
  frontend/user-guide/assets/purchase_flow_4.png
  frontend/user-guide/assets/purchase_flow_5.png
  frontend/user-guide/assets/purchase_flow_6.png
  frontend/user-guide/assets/purchase_flow_7.png
  frontend/user-guide/assets/purchase_flow_approve.png
  frontend/user-guide/assets/purchase_flow_comment.png
  frontend/user-guide/assets/purchase_flow_reject.png
  frontend/user-guide/assets/settings_ui.png
  frontend/user-guide/assets/view_dataset_in_bigquery.png
  frontend/user-guide/assets/view_expiration.png
  frontend/user-guide/assets/view_public_access.png
  frontend/user-guide/assets/view_row_level_access.png
  frontend/user-guide/assets/view_table_in_bigquery.png
  shared/commerceProcurementUtil.js
Labels: documentation

#224 Main header url fix for help
  frontend/src/components/Header.vue
Labels: bug

#235 fixes #230 - solution uses a custom Debian VM image.
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
Labels: bug

#234 Add 'messageToUser' field in the 'My Products' table
  api/v1alpha/src/policies/dataManager.js
  frontend/src/components/MyDashboardCard.vue
  frontend/src/components/ProcurementsCard.vue
Labels: enhancement

#233 Rename 'userByEmail' and 'groupByEmail' to 'user' and 'group'
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/accounts/index.js
  api/v1alpha/src/admin/bq/view/currentUserPermission.sql
  api/v1alpha/src/datasets/views/configUtil.js
  api/v1alpha/src/lib/metaManager.js
  api/v1alpha/src/policies/dataManager.js
  frontend/src/api/mock/data/entitlements.json
  frontend/src/components/EditAccount.vue
  frontend/user-guide/ACCOUNTS.md
  shared/test/commonUtilTest.js
Labels: cleanup

#241 fixes #240 - Marketplace VM solution Release Notes
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.zip
Labels: documentation

#238 Dataset account modal should only show non-table-based accounts
  api/v1alpha/src/accounts/dataManager.js
Labels: bug

#236 Adding tooltips to data-table column headers and column action buttons
  frontend/src/components/AccountsCard.vue
  frontend/src/components/DatasetsCard.vue
  frontend/src/components/MyDashboardCard.vue
  frontend/src/components/PoliciesCard.vue
  frontend/src/components/ProcurementsCard.vue
  frontend/src/components/ViewsCard.vue
Labels: enhancement, ui

#239 Updated doc name for user guide and url
  frontend/public/index.html
  frontend/src/components/Welcome.vue
Labels: cleanup, documentation

#242 Add ability to see table list in details for table-based policies
  api/v1alpha/src/policies/dataManager.js
  frontend/src/components/MyDashboardCard.vue
Labels: cleanup, enhancement

#248 fixes #246 - resolved VM solution submission error and updated release version
  marketplace/README.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.1.zip
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: bug

#254 Add marketplace links to policies list and edit policy form
  frontend/src/components/DatasetsCard.vue
  frontend/src/components/EditPolicy.vue
  frontend/src/components/MyDashboardCard.vue
  frontend/src/components/PoliciesCard.vue
  frontend/src/urlHelper.js
Labels: cleanup, enhancement, ui

#255 Add UI switch and enableAutoApprove schema field to policies
  api/v1alpha/src/admin/bq/schema/policy.json
  frontend/src/components/EditPolicy.vue
Labels: enhancement, ui

#257 PubSub account & policy integration for purchase and entitlement auto approvals
  api/v1alpha/package-lock.json
  api/v1alpha/package.json
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/datasets/dataManager.js
  api/v1alpha/src/index.js
  api/v1alpha/src/policies/dataManager.js
  api/v1alpha/src/policies/index.js
  api/v1alpha/src/procurements/dataManager.js
  shared/commerceProcurementUtil.js
  shared/pubSubUtil.js
Labels: enhancement

#258 Enable the policy form switch for modifying the enable auto approve checkbox
  frontend/src/components/EditPolicy.vue
Labels: ui

#263 Update storage path name and reflect revised directory hierarchy in docs
  examples/weather/README.md
  ingestion/batch/config.js
  ingestion/batch/configurationManager.js
  ingestion/batch/index.js
  ingestion/batch/test/configurationManagerTest.js
  ingestion/batch/test/ingestionTest.js
Labels: cleanup, enhancement

#268 Marketplace VM solution - bug fix to resolve deployment error from verification service
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.5.2.zip
  marketplace/vm-solution/c2d_deployment_configuration.json
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
  marketplace/vm-solution/waiter.jinja
Labels: bug
