Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2020-11, with the labels that each got.

#372 Install documentation updates
  DEPLOY.md
  README.md
Labels: cleanup, documentation

#371 UI should redirect to restricted page when user navigates to an unauthorized page
  frontend/src/router.js
Labels: bug, ui

#374 Document updates for domain mappings
  DEPLOY.md
Labels: documentation

#375 Project Id naming update
  README.md
Labels: documentation

#377 Dependabot security fixes
  api/v1alpha/package-lock.json
  api/v1alpha/package.json
  ingestion/streaming/package-lock.json
  ingestion/streaming/package.json
  shared/package-lock.json
  shared/package.json
Labels: cleanup

#378 Marketplace VM solution v0.6.1
  marketplace/DATA_PRODUCERS.md
  marketplace/PREREQUISITES.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.1.zip
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: bug, documentation, enhancement

#381 Marketplace integration doc updates
  frontend/user-guide/MARKETPLACE_INTEGRATION.md
Labels: documentation

#382 Remove old unused settings logic
  frontend/src/components/Footer.vue
  frontend/src/store.js
Labels: cleanup

#385 Exclude datashare dataset from view list
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/datasets/dataManager.js
  api/v1alpha/src/lib/config.js
  frontend/src/mixins/authMixin.js
  shared/bigqueryUtil.js
  shared/test/bigQueryUtilTest.js
Labels: bug, cleanup, ui
