Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2021-01, with the labels that each got.

#396 Add marketplace plan change support
  api/v1alpha/package-lock.json
  api/v1alpha/package.json
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/accounts/index.js
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/policies/dataManager.js
  api/v1alpha/src/procurements/dataManager.js
  api/v1alpha/src/procurements/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AccountsCard.vue
  frontend/src/components/EditAccount.vue
  frontend/src/components/ProcurementsCard.vue
  shared/commerceProcurementUtil.js
Labels: bug, cleanup, enhancement

#405 gcp-metadata unavailable fix
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/lib/config.js
Labels: bug

#409 View authorization when base object is within the same dataset
  api/v1alpha/src/datasets/dataManager.js
Labels: bug

#410 Setting projectId var on UI and API deploy script
  api/deploy.sh
  frontend/deploy.sh
Labels: dependencies, enhancement

#414 Deleting a view should remove the policy association if table based
  api/v1alpha/src/datasets/dataManager.js
Labels: bug, cleanup

#417 Disable ability to change a view name or dataset through edit view UI
  frontend/src/components/EditView.vue
Labels: cleanup, enhancement

#415 Validation updates to ensure duplicate views are not created
  api/v1alpha/src/datasets/views/configValidator.js
  frontend/src/components/EditView.vue
Labels: bug, cleanup, enhancement

#419 Chip highlighting fix
  api/v1alpha/src/accounts/dataManager.js
Labels: bug

#420 Save button not always enabling when policy selection changed
  frontend/src/components/EditAccount.vue
Labels: bug

#421 Marketplace v6.2
  api/deploy_ds_api.py
  api/deploy_ds_api.yaml
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.2.zip
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: bug, documentation, enhancement

#422 Fix for find marketplace account
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/policies/dataManager.js
  api/v1alpha/src/procurements/dataManager.js
Labels: bug

#424 Deleted account names are included in the procurement UI
  api/v1alpha/src/procurements/dataManager.js
Labels: bug

#427 Navigate to table button within plan details failing
  frontend/src/urlHelper.js
Labels: bug

#431 Plan change support not working for auto renewal setup
  api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/accounts/index.js
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/lib/config.js
  api/v1alpha/src/procurements/dataManager.js
  frontend/deploy.sh
  frontend/public/config/config.json
  frontend/src/api/server/index.js
  frontend/src/components/AccountsCard.vue
  frontend/src/components/AdminCard.vue
  frontend/src/components/EditAccount.vue
  frontend/src/components/EditPolicy.vue
  frontend/src/components/Header.vue
  frontend/src/components/PoliciesCard.vue
  frontend/src/components/ProcurementsCard.vue
  frontend/src/components/SetupBanner.vue
  frontend/src/components/Welcome.vue
  frontend/src/config.js
  frontend/src/store.js
  shared/pubSubUtil.js
  shared/testProcurementUtil.js
Labels: api, bug, cleanup

#437 Safari login fix
  frontend/src/browserHelper.js
  frontend/src/main.js
  frontend/src/router.js
Labels: bug

#440 fixes #439 - updates Datashare release version to 0.5.9
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.3.zip
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: enhancement

#442 PubSub permission fix and config reference error for marketplace account reset
  ENVIRONMENT_VARIABLES.md
  api/config/ds-api-mgr-role-definition.yaml
  frontend/src/components/AccountsCard.vue
Labels: bug

#444 Entitlements in state ENTITLEMENT_PENDING_CANCELLATION not handled by sync
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/procurements/dataManager.js
Labels: bug

#449 Add 'copy query' button to the my products dialog
  frontend/src/components/MyProductsCard.vue
Labels: enhancement

#448 data-producers variable in update.sh does not support multiple accounts
  APPLY_ISTIO_POLICIES.md
  api/README.md
  api/deploy.sh
  api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml
  frontend/public/config/config.json
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.4.zip
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: bug

#451 PubSub init retry and additional logs
  api/config/ds-api-mgr-role-definition.yaml
  api/deploy.sh
  api/v1alpha/package-lock.json
  api/v1alpha/package.json
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/index.js
  shared/pubSubUtil.js
Labels: bug
