Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2021-08, with the labels that each got.

#545 Marketplace 0.7.2 Release
  marketplace/README.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.7.2.zip
  marketplace/vm-solution/cluster.py
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: documentation, enhancement, cleanup

#549 Request hangs when routing to a non-existent path
  frontend/src/router.js
  frontend/src/views/404.vue
Labels: bug, cleanup

#547 Multi-project auth fix
  api/v1alpha/src/lib/auth.js
Labels: bug

#553 fixes #552
  marketplace/README.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.7.3.zip
  marketplace/vm-solution/c2d_deployment_configuration.json
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
Labels: bug

#556 processUpload function error message update for placing data files in wrong path
  ingestion/batch/configurationManager.js
Labels: cleanup

#555 Ingestion path doc fix
  ingestion/README.md
Labels: documentation, cleanup

#554 Add UI environmental variables to deploy.sh
  frontend/deploy.sh
Labels: bug, cleanup
