Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2021-04, with the labels that each got.

#472 shared vulnerability fixes
  shared/package-lock.json
Labels: cleanup

#474 front end security vulnerability fixes
  frontend/package-lock.json
  frontend/package.json
Labels: cleanup

#475 PubSub version upgrade and changed subscription retry count to 5
  api/v1alpha/package-lock.json
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/datasets/dataManager.js
  shared/bigqueryUtil.js
  shared/package-lock.json
  shared/package.json
  shared/pubSubUtil.js
Labels: bug, cleanup

#479 Marketplace Release 6.8 - fixes #478
  marketplace/PREREQUISITES.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.8.zip
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: bug

#482 Marketplace related UI fields not showing properly when VUE_APP_MARKETPLACE_INTEGRATION set to true in cloud run vars
  frontend/src/config.js
Labels: bug

#484 Marketplace activation failing for non logged in user
  frontend/src/components/ActivationCard.vue
  frontend/src/router.js
Labels: bug

#486 Change marketplace jwt handoff to use session storage
  frontend/src/components/ActivationCard.vue
Labels: cleanup

#489 Doc: Add doc for createdBy
  api/v1alpha/src/accounts/index.js
  api/v1alpha/src/datasets/index.js
  api/v1alpha/src/policies/index.js
Labels: bug, cleanup, documentation
