Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2021-03, with the labels that each got.

#468 Marketplace Release 6.7 - fixes #467
  DATASHARE_API_MGR_SETUP.md
  README.md
  api/deploy_ds_api.py
  marketplace/PREREQUISITES.md
  marketplace/create-datashare-service-account.sh
  marketplace/create-vm-solution-package.sh
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.7.zip
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: documentation, enhancement

#470 Marketplace doc link fix
  marketplace/PREREQUISITES.md
Labels: bug, cleanup

#471 Security fixes
  api/v1alpha/package-lock.json
  frontend/package-lock.json
  ingestion/batch/package-lock.json
  ingestion/streaming/package-lock.json
Labels: cleanup
