Repository GoogleCloudPlatform/datashare-toolkit, pull requests merged in 2021-02, with the labels that each got.

#456 Move getTableFqdn functions to config
  api/v1alpha/src/accounts/dataManager.js
  api/v1alpha/src/admin/dataManager.js
  api/v1alpha/src/datasets/dataManager.js
  api/v1alpha/src/datasets/views/configValidator.js
  api/v1alpha/src/policies/dataManager.js
  api/v1alpha/src/procurements/dataManager.js
  shared/bigqueryUtil.js
Labels: cleanup

#458 Navigate to dataset not opening dataset page
  frontend/src/urlHelper.js
Labels: bug

#461 'Manage on provider' button fix
  api/v1alpha/istio-manifests/1.4/authz/allow-marketplace-service-account-policy.yaml
  api/v1alpha/src/procurements/index.js
Labels: api

#465 Marketplace issue 321
  api/deploy_ds_api.py
  frontend/deploy_ui_cloud_run.py
  marketplace/PREREQUISITES.md
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.5.zip
  marketplace/vm-solution/datashare-vm.jinja
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
  marketplace/vm-solution/waiter.jinja
Labels: bug, cleanup, enhancement

#466 fixes #454 - updated Datashare to v0.6.5, fixed a minor bug in cratin…
  marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
  marketplace/releases/datashare-marketplace-vm-solution-v0.6.6.zip
  marketplace/vm-solution/datashare-vm.jinja.display
  marketplace/vm-solution/datashare-vm.jinja.schema
Labels: bug, documentation, enhancement
